#for i in $(find -type f -name '*.dat') ; do 
#    echo -n $i": " ; 
#    (.quickplot_ascii.py $i) ; 
#done

./quickplot_ascii.py AVHRR06_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR06_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR06_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR06_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR06_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR06_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR06_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR06_G_independent_Ch2.dat 
./quickplot_ascii.py AVHRR06_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR06_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR06_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR06_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR06_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR06_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR06_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR06_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR06_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR06_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR07_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR07_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR07_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR07_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR07_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR07_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR07_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR07_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR07_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR07_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR07_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR07_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR07_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR07_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR07_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR07_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR07_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR07_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR08_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR08_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR08_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR08_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR08_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR08_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR08_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR08_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR08_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR08_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR08_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR08_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR08_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR08_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR08_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR08_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR08_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR08_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR09_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR09_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR09_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR09_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR09_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR09_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR09_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR09_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR09_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR09_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR09_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR09_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR09_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR09_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR09_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR09_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR09_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR09_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR10_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR10_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR10_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR10_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR10_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR10_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR10_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR10_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR10_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR10_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR10_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR10_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR10_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR10_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR10_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR10_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR10_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR10_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR11_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR11_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR11_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR11_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR11_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR11_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR11_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR11_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR11_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR11_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR11_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR11_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR11_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR11_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR11_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR11_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR11_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR11_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR12_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR12_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR12_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR12_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR12_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR12_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR12_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR12_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR12_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR12_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR12_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR12_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR12_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR12_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR12_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR12_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR12_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR12_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR14_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR14_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR14_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR14_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR14_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR14_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR14_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR14_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR14_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR14_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR14_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR14_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR14_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR14_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR14_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR14_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR14_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR14_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR15_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR15_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR15_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR15_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR15_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR15_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR15_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR15_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR15_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR15_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR15_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR15_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR15_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR15_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR15_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR15_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR15_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR15_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR16_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR16_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR16_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR16_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR16_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR16_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR16_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR16_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR16_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR16_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR16_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR16_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR16_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR16_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR16_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR16_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR16_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR16_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR17_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR17_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR17_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR17_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR17_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR17_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR17_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR17_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR17_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR17_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR17_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR17_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR17_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR17_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR17_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR17_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR17_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR17_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR18_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR18_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR18_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR18_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR18_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR18_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR18_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR18_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR18_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR18_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR18_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR18_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR18_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR18_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR18_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR18_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR18_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR18_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRR19_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRR19_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRR19_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRR19_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRR19_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRR19_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRR19_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRR19_G_independent_Ch2.dat
./quickplot_ascii.py AVHRR19_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRR19_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRR19_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRR19_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRR19_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRR19_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRR19_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRR19_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRR19_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRR19_G_structured_Ch5.dat 

./quickplot_ascii.py AVHRRMTA_G_measurement_Ch1.dat 
./quickplot_ascii.py AVHRRMTA_G_measurement_Ch2.dat 
./quickplot_ascii.py AVHRRMTA_G_measurement_Ch3a.dat 
./quickplot_ascii.py AVHRRMTA_G_measurement_Ch3b.dat 
./quickplot_ascii.py AVHRRMTA_G_measurement_Ch4.dat 
./quickplot_ascii.py AVHRRMTA_G_measurement_Ch5.dat
./quickplot_ascii.py AVHRRMTA_G_independent_Ch1.dat 
./quickplot_ascii.py AVHRRMTA_G_independent_Ch2.dat
./quickplot_ascii.py AVHRRMTA_G_independent_Ch3a.dat 
./quickplot_ascii.py AVHRRMTA_G_independent_Ch3b.dat 
./quickplot_ascii.py AVHRRMTA_G_independent_Ch4.dat 
./quickplot_ascii.py AVHRRMTA_G_independent_Ch5.dat 
./quickplot_ascii.py AVHRRMTA_G_structured_Ch1.dat 
./quickplot_ascii.py AVHRRMTA_G_structured_Ch2.dat 
./quickplot_ascii.py AVHRRMTA_G_structured_Ch3a.dat 
./quickplot_ascii.py AVHRRMTA_G_structured_Ch3b.dat 
./quickplot_ascii.py AVHRRMTA_G_structured_Ch4.dat 
./quickplot_ascii.py AVHRRMTA_G_structured_Ch5.dat 

